version: '3.8'
services:
  nestjs:
    container_name: nestjs
    image: node:18
    ports:
      - '64550:64550'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    stop_grace_period: 0s
    working_dir: /usr/src/app
    command: sh ./runNestjs.sh
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=dev
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
