version: '3.8'
services:
  nestjs:
    container_name: nestjs
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    stop_grace_period: 0s
    ports:
      - '64550:64550'
    depends_on:
      - postgres
    command: sh ./runNestjs.sh
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5555:5555'
