version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=dev
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
